package engine;

import java.util.Random;

public class NameGenerator {
	
	   private static String[] Female =	{ "Martha", "Susan", "Charlene", "Sandra", "Teri", "Nettie", "Norma", "Cathy", "Marina", "Etta", "Susan", "Briana", "Lorna", "Cristina", "Beatrice", "Constance", "Betty", "Carmelina", "Santina", "Edith", "Rita", "Josephine", "Natalie", "Lisa", "Stacey", "Mary", "Jennifer", "Albertine", "Evelyn", "Margaret", "Wanda", "Donna", "Pam", "Minnie", "Sandra", "Dorothy", "Dawn", "Sharon", "Wanda", "Corinne", "Eileen", "Jena", "Susan", "Loretta", "Alice", "Lydia", "Patricia", "Glenda", "Mabel", "Clara", "Jenise", "Linda", "Sandra", "Gloria", "Leta", "Jennifer", "Alma", "Lauren", "Bobbie", "Margret", "Anita", "Kellie", "Patricia", "Suzanne", "Angela", "Maria", "Roxanna", "Eugenia", "Constance", "Tracey", "Sheri", "Linda", "Carmen", "Marcia", "Angela", "Yvette", "Ida", "Teresa", "Clare", "Catherine", "Sharon", "Stephanie", "Maudie", "Elaine", "Michelle","Myrna", "Robin", "Jean", "Virginia", "Elizabeth", "Ruth", "Ann", "Valerie", "Ruth", "Sue", "Diana", "Melinda", "Myrna", "Beth", "Sandra", "Betty", "Genevieve", "Tiffaney", "Anne", "Rebekah", "Laura", "Martha", "Susan", "Lena", "Karin", "Fern", "Renate", "Diane", "Vera", "Rebecca", "Karen", "Rocio", "Mary", "Dorothy", "Catherine", "Sheena", "Carmela", "Carol", "Bertha", "Mary", "April", "Tina", "Mary", "Tiffany", "Maureen", "Tracie", "Carol", "Josie", "Lisa", "Rosa", "Gabriela", "Ana", "Marlene", "Cheryl", "Velma", "Lucy", "Tabitha", "Larita", "Debra", "Anne", "Ebony", "Katherine", "Jamie", "Inga", "Shirley", "Marcela", "Stephanie", "April", "Maxine", "Fran", "Jean", "Jennie", "Janis", "Eula", "Alexis", "Connie", "Mary", "Lenore", "Mary", "Betty", "Lori", "Carline", "Carol", "Candy", "Marget", "Maria", "Teresa", "Michelle", "Anna", "Martha", "Alicia", "Justine", "Deborah", "Cecelia", "Cleo", "Sheri", "Tracey", "Jane", "Sandra", "Sarah", "Veronica", "Carol", "Jennifer", "Mary", "Kelly", "Lynette", "Juliet", "Allison", "Patricia", "Ann", "Margaret", "Angela", "Anna", "Shirley", "Erica" };
	   private static String[] Male =	{ "Michael", "Keith", "Billy", "Kenneth", "Christopher", "Terry", "Terry", "Ralph", "William", "Charles", "Oscar", "Nicholas", "William", "George", "Thomas", "Benjamin", "Richard", "Leon", "Matthew", "Peter", "Bryan", "James", "Gordon", "Leonard", "Dustin", "Freddy", "Gary", "Melvin", "Herschel", "Jason", "Troy", "Otto", "Trinidad", "Ryan", "Daniel", "Albert", "Anthony", "Donald", "Frank", "Micheal", "William", "Kenneth", "Mitchell", "Greg", "Mathew", "Kenneth", "Gregg", "Vernon", "Luther", "James", "Julio", "Charles", "Willie", "Steven", "Joshua", "David", "Jason", "Edward", "Mark", "William", "Roy", "Stanley", "Cory", "Malcolm", "Pedro", "John", "Chester", "John", "Philip", "David", "George", "Jack", "Bernard", "Jeremy", "Rickey", "Joshua", "Russell", "Gabriel", "Craig", "Christopher", "John", "James", "Ryan", "Stephen", "Ronald", "Walter", "Donald", "Anthony", "William", "Justin", "Arlen", "Robert", "Franklin", "Albert", "Jeffrey", "Brian", "James", "Mark", "Dennis", "William", "Kenneth", "Jose", "Jonathan", "Stephen", "Danny", "Richard", "Louis", "Alfred", "Alvin", "Christopher", "Michael", "Alberto", "Bernie", "Alvin", "Michael", "William", "John", "Russ", "Edward", "James", "Jesus", "Edward", "Robert", "Frank", "Jeffery", "Timothy", "Derrick", "Brandon", "Eric", "Jay", "Fred", "Joshua", "Johnnie", "Steven", "Derrick", "Steven", "Scott", "Douglas", "John", "Carl", "Joe", "James", "Gary", "Mark", "Brad", "Gerald", "Willie", "Joel", "Timothy", "Carlton", "John", "George", "David", "Darin", "Jose", "James", "Curtis", "Steven", "Gary", "Ronald", "George", "Wayne", "Calvin", "Richard", "Leonard", "Harley", "Tommy", "Joseph", "Joshua", "Steven", "John", "Emile", "Jeff", "Lloyd", "Clint", "Russell", "Danny", "Brian", "Timothy", "Arthur", "Dennis", "Cory", "Doug", "Anthony", "Jarvis", "Dustin", "Cory", "Mitchell", "Douglas", "Benjamin", "Ray", "Michael", "Derek", "Edward", "Abraham", "Rick", "Ronald", "Anthony", "Larry", "Jeff" };
	   private static String[] Last =	{ "Davidson", "Macaraeg", "Lucas", "Reid", "Brooks", "Evens", "Zingler", "Paugh", "Alvarado", "Anderson", "Gimenez", "Nichell", "Parker", "Farrish", "Brock", "Gaines", "Wright", "Bodin", "Woods", "Jones", "White", "Mixon", "Leal", "Anderson", "White", "Seawright", "Frawley", "Stinchfield", "Hardman", "Baillargeon", "Beighley", "Tousom", "Livingston", "Farley", "Demars", "Olson", "Gonzalez", "Jones", "Brown", "Shisler", "Herbert", "Blum", "Lanius", "Granstrom", "Wesson", "Blechman", "Brewer", "Price", "Goodwin", "Landrus", "Rhodd", "Manzanares", "Jackson", "Glover", "Hartzell", "Whitesel", "Villa", "Sussman", "Schwartz", "Ishihara", "Oliver", "Paulson", "Shaw", "Thomas", "Dennison", "Greenhalgh", "Stokes", "Gibson", "Kallman", "Royster", "Williams", "Irwin", "Hanson", "Jackson", "Graham", "Easterwood", "Campbell", "Jackson", "Villa", "Wallack", "Lalley", "Fenwick", "Gonzalez", "Griffin", "Smith", "Bell", "Smith", "Sengbusch", "Kiernan", "Glover", "Bridges", "Cobb", "Rembert", "Hall", "Johnston", "Lambert", "Maupin", "Ivie", "Burris", "Peterson", "Hibler", "Betancourt", "Ehlert", "Grambo", "Hardin", "Badilla", "Campbell", "Casey", "Netzer", "Berenbaum", "Taylor", "Brewer", "Hunt", "Tighe", "Nease", "Bostic", "Banks", "Olaughlin", "Bennett", "Mckinley", "Cooper", "Lear", "Evener", "Mcevoy", "Cruz", "Bostick", "Neumann", "Callaway", "Gerber", "Billings", "Persons", "Clark", "Born", "Dean", "Stahlman", "Crase", "Patton", "Bernal", "Lee", "Noyola", "Howell", "Davis", "Brown", "Heberling", "Dickey", "Harper", "Santos", "Fish", "Bejaran", "Hawkins", "Thomas", "Raymond", "Gibbs", "Robey", "Yancey", "Updike", "Burkett", "Bass", "Deare", "Sandoval", "Prochak", "Campbell", "Garza", "Campos", "Bates", "Mayne", "Janicki", "Olivero", "Tindol", "Navarro", "Palmer", "Kelly", "Fornili", "Graves", "Augusto", "Anderson", "Smith", "Wallace", "Sanders", "Rivero", "Amos", "Coleman", "Ballard", "Jones", "Miller", "Hartranft", "Baines", "Laughlin", "Bevins", "Jones", "Walston", "Coll", "Ball", "Shriver", "Austin", "Hibbitt", "Robins", "Cox", "Ferguson", "Wollenburg" };
		   
	   private static Random rand = new Random();

	   public static String generateFemaleName() {
		   return  Female[rand.nextInt(Female.length)] + " " +
				   Last[rand.nextInt(Last.length)];
		   }
	   
	   public static String generateMaleName() {
		   return  Male[rand.nextInt(Male.length)] + " " +
				   Last[rand.nextInt(Last.length)];
		   }

}
